baseURL = 'https://m4xshen.me'
languageCode = 'en-us'
title = 'Max Shen'
theme = 'paper'
paginate = 5

googleAnalytics = 'UA-348126858'
disqusShortname = 'm4xshen'

[author]
  name = 'Max Shen'

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  description = "Hi I'm Max Shen. Here's my personal blog where I share my learning journey to help and inspire other people. I post tutorial about Vim, Linux and programming."
  github = 'm4xshen'
  rss = true
  avatar = 'm4xshen@gmail.com'
  name = 'Max Shen'
  bio = 'I learn new things consistently and share on this blog'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
