baseURL = 'https://m4xshen.github.io'
languageCode = 'en-us'
title = 'm4xshen'
theme = 'paper'

googleAnalytics = 'UA-348126858'
disqusShortname = 'm4xshen'

[params]

github = 'm4xshen'

avatar = 'm4xshen@gmail.com'
name = 'Max Shen'
bio = 'I learn new things consistently and share on this blog'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
