baseURL = 'https://m4xshen.dev'
languageCode = 'en-us'
title = 'Max Shen Dev'
theme = 'slash'

googleAnalytics = 'G-H19K5X8RCB'
disqusShortname = 'max-shen-dev'

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[menu]
[[menu.main]]
  name = 'Posts'
  url = '/posts'
  weight = 10
[[menu.main]]
  name = 'Projects'
  url = '/projects'
  weight = 20
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 30

[markup]
  [markup.highlight]
    style = 'github-dark'

[params]
  author = 'Max Shen'
  intro = "I'm an open source and front-end web developer from Taiwan, passionate about solving problems by making projects about Neovim and Web."
